"""empty message

Revision ID: 138ca053897c
Revises: 3213e4442576
Create Date: 2015-05-09 10:20:27.572821

"""

# revision identifiers, used by Alembic.
revision = '138ca053897c'
down_revision = '3213e4442576'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
