"""cancel default value of category

Revision ID: 160512df3731
Revises: 3571fc573502
Create Date: 2015-04-30 00:03:50.064264

"""

# revision identifiers, used by Alembic.
revision = '160512df3731'
down_revision = '3571fc573502'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
