"""add default value for category column

Revision ID: 17c4e2101cd5
Revises: 160512df3731
Create Date: 2015-04-30 11:00:12.691268

"""

# revision identifiers, used by Alembic.
revision = '17c4e2101cd5'
down_revision = '160512df3731'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
