"""add category

Revision ID: 2bd31054c1b2
Revises: None
Create Date: 2015-04-29 23:53:13.355480

"""

# revision identifiers, used by Alembic.
revision = '2bd31054c1b2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('category', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'category')
    ### end Alembic commands ###
