"""empty message

Revision ID: 3016a8edcc0d
Revises: 17c4e2101cd5
Create Date: 2015-04-30 12:43:43.835738

"""

# revision identifiers, used by Alembic.
revision = '3016a8edcc0d'
down_revision = '17c4e2101cd5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
