"""empty message

Revision ID: 3213e4442576
Revises: None
Create Date: 2015-05-09 02:03:47.530391

"""

# revision identifiers, used by Alembic.
revision = '3213e4442576'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
