"""set default value for category

Revision ID: 3571fc573502
Revises: 2bd31054c1b2
Create Date: 2015-04-29 23:59:59.088373

"""

# revision identifiers, used by Alembic.
revision = '3571fc573502'
down_revision = '2bd31054c1b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
